### ISSUE TITLE
wix embedded mysql

### ISSUE THREAD

**Issue by michaeljamieson10** [XenoAmess/x8l_idea_plugin#40]
Hello! I do not know of any other way of commmunicating with a developer here. Do you know how to get into contact  to the developers for the wix embedded mysql project? I would really appreciate it, you can reach me at michaeljamieson10@gmail.com

**Comment by XenoAmess** [comment]
> Hello! I do not know of any other way of commmunicating with a developer here. Do you know how to get into contact to the developers for the wix embedded mysql project? I would really appreciate it, you can reach me at [michaeljamieson10@gmail.com](mailto:michaeljamieson10@gmail.com)

sorry but I have no way to find him neither......
